### ISSUE TITLE
Update to SDK v3 or v4

### ISSUE THREAD

**Issue by invidian** [newrelic/nri-kubernetes#145]
`v2.0.1-0.20180410150501-14a5386f9150+incompatible` version is used right now, while there is v4.1 already released.

**Comment by paologallinaharbur** [comment]
SDKv4 brings new functionalities, but at the same time a really big breaking change (due to the change between samples and dimensional metrics) and bumping that is really expensive at least for now. We are doing that for vSphere and with that knowledge we can wait the effort needed to do the same here 

Moving to SDKv3 is less expensive and we could researcha bit if possible

**Comment by invidian** [comment]
https://github.com/newrelic/infra-integrations-sdk/blob/sdk_v4-migration_from_v3/docs/v2tov3.md
