### ISSUE TITLE
Modify autodiscovery for KSM considering new Arch

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/nri-kubernetes#217]
Taking into account that only one component needs to scrape KSM and that the process needs to be long-running we could simplify greatly autodiscovery.

**Comment by roobre** [comment]
Thanks for the recap @invidian!
Some thoughts I have for KSM discovery use cases:

As an `nri-kubernetes` user, I want to:
- Get KSM discovered out of the box when it's installed together with the `nri-bundle` helm chart
- Get KSM discovered if its not bundled, so I can reuse an existing KSM installation
- Manually specify a KSM endpoint URL, which would override all discovery mechanisms
- Make the autodiscovery cheap so it doesn't bring my cluster down if pod is restarted often (e.g. in `CrashLoopBackoff`)

On the tehcnical side:
- We want to have full support for sharded KSM in the future, but I wouldn't say it's required now. However, what we _do_ know is that users often have two or more KSM instances in their cluster, either by mistake or to have multiple KSM versions. We must make sure that "automatic sharding support" does not conflict with this, far mor common, use case.
- Right now we discover pods and then attack their podIPs, but I'm not sure if we want to keep doing that. I find more appealing to try to get _services_ using `labelSelector` instead, or is this not good for some other reason I'm not seeing?
  - Bonus: If we attack the service, we get KSM HA essentially for free, right?
- It would be nice if the details of how service/pod is discovered, such as the labelSelector or port number/name were configurable, defaulting to the values KSM authors set on its helm chart.
- Limiting the discovery to a namespace was done to avoid hammering the APIServer with expensive requests. I believe that this should be less pressing now since there will be few agents asking for KSM, but we can keep the option just in case it helps any corner case. I don't think it's hard to honor.

**Comment by invidian** [comment]
>We want to have full support for sharded KSM in the future, but I wouldn't say it's required now. However, what we do know is that users often have two or more KSM instances in their cluster, either by mistake or to have multiple KSM versions. We must make sure that "automatic sharding support" does not conflict with this, far mor common, use case.

Good point. They should be deployed until different label selector then I assume? If not, do we still want to scrape only one instance by default and conditionally enable support for multiple then?

>Right now we discover pods and then attack their podIPs, but I'm not sure if we want to keep doing that. I find more appealing to try to get services using labelSelector instead, or is this not good for some other reason I'm not seeing?

Yes, we should be using service endpoints instead (which are effectively pod IPs as well, but 

>Bonus: If we attack the service, we get KSM HA essentially for free, right?

KSM does not support HA. Only sharding. So we shouldn't hit the service. Also KSM manifests only deploy headless services, so it's not even possible.
