### ISSUE TITLE
Support environment variables for setting scrape interval

### ISSUE THREAD

**Issue by SerhiiK** [newrelic/nri-kubernetes#51]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when trying to set interval for windows agent

## Feature Description
I would like to set interval in file nri-kubernetes-definition.yml or nri-kubernetes-definition-windows.yml through env var for container like NRIA_LICENSE_KEY

## Describe Alternatives
To have possibility to edit files inside the image.

## Additional context
Try to change interval for calling new-relic

## Priority
Really Want it

**Comment by roobre** [comment]
Hi, thanks for raising this concern.

While this is not currently possible with an environment variable, our Helm chart does allow to override integration configuration files inside the image. Please check the `integrations_config` properti in https://github.com/newrelic/helm-charts/tree/master/charts/newrelic-infrastructure.

**Comment by fr-ser** [comment]
Maybe this relates to this issue here (https://github.com/newrelic/nri-kubernetes/issues/83) but it seems like the helm chart does **not** support settings this value right now.

See NewRelic forum post: <https://discuss.newrelic.com/t/configure-polling-interval-for-kubernetes-integration/140289/4?u=sergej.herbert>

So, is setting the scrape interval not possible at all right now when deploying via the helm chart?

**Comment by gsanchezgavier** [comment]
thanks @fr-ser  as you point this is related to #83 and also to [this issue](https://github.com/newrelic/helm-charts/issues/344) on the helm-chart repo.
