### ISSUE TITLE
Fix rounding issue for allocatableCPUCores

### ISSUE THREAD

**Issue by bpschmitt** [newrelic/nri-kubernetes#75]
## Description

It appears we are rounding the `allocatableCPUCores` attribute and we should not be.  I've attached the results in Query Builder and the raw JSON returned by NRDB.  It's probably worth sanity checking related attributes to ensure we're not rounding others as well.

![image](https://user-images.githubusercontent.com/9002169/108881154-a2319700-75c8-11eb-82d3-c54788777174.png)

![image](https://user-images.githubusercontent.com/9002169/108881277-becdcf00-75c8-11eb-99e2-00dd91d302e3.png)

## Expected Behavior

I would expect the `allocatedCPUCores` attirbute to reflect what is returned by the `kubectl` output.

## Your Environment
EKS v1.17.12-eks-7684af
New Relic Infra: `newrelic/infrastructure-k8s:2.2.0`

**Comment by roobre** [comment]
The problem seems to stem from `src/kubelet/metric/resource.go:36`, where the value is fetched using `resourceQuantity.Value()`:
> `// Value returns the value of q; any fractional part will be lost.`

Using `MilliValue` should fix the issue. However, right now `allocatableMemory` and `allocatableCPUCores` follow the same code path. A small change would be required to refactor this.
