### ISSUE TITLE
Put default configuration in /etc/newrelic rather than /var/db/newrelic

### ISSUE THREAD

**Issue by roobre** [newrelic/nri-kubernetes#83]
Currently, the Dockerfile copies the integration config to `/var/db/newrelic-infra/integrations.d/nri-kubernetes-config.yml`:
https://github.com/newrelic/nri-kubernetes/blob/c87090aa031b06c1c714e529008ea3fa63f4c8d7/Dockerfile#L12

This makes it hard for the user to override this file, specially when the helm chart is in use. This file could instead be dropped in `/etc/newrelic-infra/integrations.d/`, where the user is allowed to create (and therefore override) files with the `integrations_config` property of the helm chart.

**Comment by gsanchezgavier** [comment]
Also to support the possibility to change the interval of the integration the config file should be changed to the [new configuration format](https://docs.newrelic.com/docs/create-integrations/infrastructure-integrations-sdk/specifications/host-integrations-newer-configuration-format/) (v4)  since the current one defines the interval in the `definition.yml` file.

**Comment by roobre** [comment]
Indeed, we need to keep this in mind. However the change should not be very complex, and there would be no breakage since there are no packages for `nri-kubernetes`.

**Comment by paologallinaharbur** [comment]
Now in "develop" the configuration is hosted in "FilePath = "/etc/newrelic-infra/integrations.d/""
